### ISSUE TITLE
How to install convential_changelog?

### ISSUE THREAD

**Issue by ghost** [smichard/conventional_changelog#28]
I want to use `conventional_changelog` on my local environment, when I'm pushing through the GitHub desktop (on my windows machine).

I'm not a professional open source programmer, and it's not obvious to me how to make it work (maybe like I'm used to do, through trials and errors).

I'm not sure about how to use it. _Maybe I have to install the smichard/conventional_changelog in my local repo. Or maybe I can install it globally?_

Another question is, _if there is possibly to use `generate_changelog_local.sh` without installing the hole package_.

I will be very happy to getting know how to use this script in a easy way.
I'm really sorry that I have to ask this silly question.

PS! I have no experience or knowledge using .github/workfows.

**Comment by smichard** [comment]
https://www.opensourcerers.org/2024/03/25/enhancing-code-project-documentation-through-automated-changelogs/

Thank you for reaching out and for your interest in using Conventional Changelog! Here are a few ways you can use the tool in your local environment:

**Native Usage on Linux**
If you have access to a Linux environment, you can run the script natively. Simply navigate to your repository directory and execute:
```
./generate_changelog_local.sh
```
This will generate the changelog directly from your commit history.

**Using a Container Engine on Windows**
Since you're using Windows, the recommended approach is to use a container engine like Docker or Podman. This ensures a consistent environment without needing to install dependencies directly on your machine.

1. Build the Container Image:
First, build the container image using the provided Dockerfile. Open a terminal (e.g., Command Prompt, PowerShell) and run:
```
podman build -t conventional_changelog -f Dockerfile
# Or if using Docker
docker build -t conventional_changelog -f Dockerfile
```

2. Run the Container:
Then, run the container and mount your local repository directory to the container:
```
podman run -it --rm -v "$(pwd):/repo" conventional_changelog sh
# Or if using Docker
docker run -it --rm -v "$(pwd):/repo" conventional_changelog sh
```

3. Execute the Script Inside the Container:
Inside the container, navigate to the mounted repository directory and execute the script:
```
cd repo
./generate_changelog_local.sh
```

**Using GitHub Actions**
If you'd like to automate the process so that the changelog updates every time you push changes, you can use GitHub Actions. Here’s a quick overview:

Add a Workflow Configuration:
Create a new file in your repository at `.github/workflows/generate_changelog.yml` and add the following configuration:

```
name: Generate Changelog

on:
  push:
    branches: [ main ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Generate and Commit Changelog

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Generate Changelog
      uses: smichard/conventional_changelog@2.0.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Git User Info
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'

    - name: Commit Changelog
      run: |
        git add CHANGELOG.md
        git commit -m "docs: :robot: changelog file generated" || echo "No changes to commit"
        git push
```
This setup ensures that every time you push changes to the main branch, the changelog will be automatically updated and committed.

**Conclusion**
I hope this helps! Feel free to try these methods and see which one fits best with your workflow. If you run into any issues or have more questions, don’t hesitate to ask. We're here to assist you in making the best use of Conventional Changelog.
